### ISSUE TITLE
generate test loanbook

### ISSUE THREAD

**Issue by EvgenyPetrovsky** [2DegreesInvesting/pacta#2]
I want to generate loanbook using my own list of Company names.

**Comment by ghost** [comment]
Hey Evgeny, I think this is very useful, I incorporated it into a develop branch so i can play around with it a little bit and see if anything breaks (trying to keep master clean and as release ready as possible). Can we close this issue?

**Comment by EvgenyPetrovsky** [comment]
Hi @jhoff-2dii ,

I'm fine about it. We had a need to be able to generate another test loan book providing our own list names and avoiding changing a package. List of fields:
* Name;
* Sector (or NAICS);
* Country.

This is very similar to what we have in /data-raw/test-loanbook.csv. Generation logic (which is now in /data-raw/test-loanbook.R script) I was going to put into function and leave only data read from csv and function call in original R script.
